Adicionando introdução aos fundos e corrigindo tamanho da fonte e nom…
albersonmiranda/econdashboard pull request #19
Opened 2021-11-08 20:19 UTC by ramosgislaine

…es dos graficos

2021-11-08 20:57 UTC, albersonmiranda requested changes
Alterar a introdução para uma versão definitiva

2021-11-11 18:57 UTC, IsabellyPassos approved these changes
Fonte corrigida e nova introdução.

2021-11-11 19:10 UTC, IsabellyPassos approved these changes

2021-11-11 19:48 UTC, albersonmiranda approved these changes

2021-11-11 19:48 UTC, merged